### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [MattMores/req.body#5]
Hello! 

I am reviewing all group wikis today and wanted to drop a few things here that I would like y'all to take care of.

## General
- [x] Add links to all of your wiki pages on the home page

## Schema
- [x] Add your schema to your wiki, either by embedding an image of your DB diagram or by writing out your tables in markdown tables.

## User Stories
- [x] You have a few extra lines in between bullet points in Tasks > Viewing Tasks

## API Routes
- [x] Add the paths you will use to your wiki.

Once these are taken care of, please drop your responses/updates here as a response to this issue.

Thanks, y'all!!
Ed

**Comment by Code-E-Brown** [comment]
Feedback addressed.
